version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
    - 8080:80
    volumes:
    - ./:/app
    - ./docker/nginx/:/etc/nginx/
    depends_on:
    - php

  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
    - ./:/app
    - /app/vendor